version: '3'
services:
  Frontend:
    image: drupal
    ports:
    - 8081:8081
    networks:
    - mydrupal
  Backend:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=123456
    networks:
    - mydrupal
networks:
  mydrupal:

 