version: '3'
services:
  Frontend:
    image: drupal
    ports:
    - 8080:8080
    networks:
    - mydrupal
  Backend:
    image: postgres
    Environment:
    - POSTGRES_PASSWORD=123456
    networks:
    - mydrupal
networks:
  mydrupal:

 